export interface DocSubItem {
  id: string;
  title: string;
  badge?: string;
  description: string;
  readingTime: string;
  toc: { id: string; label: string }[];
  content: {
    summary: string;
    sections: {
      id: string;
      heading: string;
      lead?: string;
      paragraphs?: string[];
      codeSnippets?: {
        language: string;
        filename?: string;
        code: string;
        description?: string;
      }[];
      tables?: {
        headers: string[];
        rows: string[][];
        caption?: string;
      };
      callouts?: {
        type: "info" | "warning" | "tip" | "danger";
        title: string;
        body: string;
      }[];
      mathFormula?: string;
      subsections?: {
        id: string;
        title: string;
        body: string;
        code?: string;
        language?: string;
      }[];
    }[];
  };
}

export interface DocCategory {
  id: string;
  title: string;
  badge?: string;
  iconName: string;
  items: DocSubItem[];
}

export const DOCS_TAXONOMY: DocCategory[] = [
  /* ─────────────────────────────────────────────────────────
     01. GETTING STARTED & FOUNDATIONS
  ───────────────────────────────────────────────────────── */
  {
    id: "getting-started",
    title: "Getting Started",
    badge: "Foundations",
    iconName: "BookOpen",
    items: [
      {
        id: "overview",
        title: "Platform Overview & Architecture",
        badge: "Core",
        description: "Why deterministic runtime governance supersedes passive post-hoc audit dashboards.",
        readingTime: "6 min read",
        toc: [
          { id: "the-governance-gap", label: "The AI Governance Gap" },
          { id: "two-layer-defense", label: "Two-Tier Defense Model" },
          { id: "deterministic-vs-probabilistic", label: "Deterministic vs Probabilistic" },
          { id: "threat-model", label: "Threat Model & Trust Boundaries" },
        ],
        content: {
          summary: "Anchor is a sovereign, in-process runtime governance platform designed to prevent autonomous agent hallucinations, rogue API executions, and regulatory non-compliance before bytecode executes.",
          sections: [
            {
              id: "the-governance-gap",
              heading: "The AI Governance Gap",
              lead: "Traditional AI observability tools (Datadog LLM, LangSmith, Arize) operate purely post-hoc. They capture traces after execution has finished. If an autonomous agent triggers a fraudulent $500,000 settlement or exfiltrates confidential PII, an alert in a dashboard does nothing to prevent the damage.",
              paragraphs: [
                "Anchor changes the governance paradigm from passive post-hoc auditing to hard, synchronous, in-process runtime enforcement.",
                "Every model tool call, database execution, and agentic parameter is intercepted within the running process memory, verified against compiled statutory invariants, and sealed into an append-only SHA-256 cryptographic chain before reaching production infrastructure.",
              ],
              callouts: [
                {
                  type: "info",
                  title: "Key Principle: Zero-Trust Runtime Boundary",
                  body: "Anchor treats all LLM outputs and agentic tool invocations as untrusted external user inputs. No code or API call generated by an autonomous system is permitted to execute without cryptographic and statutory verification.",
                },
              ],
            },
            {
              id: "two-layer-defense",
              heading: "Two-Tier Defense Model",
              lead: "Anchor enforces governance across two distinct layers of the software development and execution lifecycle:",
              tables: {
                headers: ["Layer", "Mechanism", "Execution Point", "Latency Target", "Primary Purpose"],
                rows: [
                  ["Layer 1: Static AST Gatekeeper", "Tree-sitter static analysis & .anchor linting", "Pre-commit & CI/CD Pipeline", "0 ms runtime overhead", "Prevents un-instrumented code & structural policy violations from reaching master branches."],
                  ["Layer 2: In-Process Interceptor", "Native Rust C-ABI kernel & zero-copy memory buffers", "In-Process Function Invocation", "< 15–350 microseconds", "Synchronously intercepts arguments, validates risk boundaries, blocks rogue calls, and issues deterministic self-healing directives."],
                  ["Decision Audit Chain (DAC)", "Append-only SHA-256 Merkle tree ledger with Ed25519 signatures", "Asynchronous background queue", "Non-blocking (< 10 µs queue)", "Generates mathematically verifiable, tamper-evident audit dossiers for statutory subpoena readiness."],
                ],
              },
            },
            {
              id: "deterministic-vs-probabilistic",
              heading: "Deterministic Invariants vs Probabilistic LLM Judges",
              lead: "Why Anchor rejects LLM-as-a-Judge for mission-critical compliance.",
              paragraphs: [
                "Many legacy systems attempt to evaluate compliance by calling a secondary LLM (e.g. GPT-4) to judge if an agent's response was safe. This approach fails in institutional finance and healthcare for three fatal reasons:",
                "1. Non-Determinism: An LLM judge can evaluate the exact same payload differently across attempts, violating fundamental legal predictability standards.",
                "2. Latency Penalty: Remote LLM evaluations add 400ms to 2,500ms of network latency per agent step, destroying high-frequency performance.",
                "3. Vulnerability to Jailbreaks: Secondary LLMs are susceptible to prompt injection and indirect goal manipulation.",
                "Anchor compiles human laws (EU AI Act, RBI FREE-AI, SEC Reg SCI) into formal mathematical AST invariants and zero-copy Rust bytecode that executes deterministically in sub-millisecond time.",
              ],
            },
            {
              id: "threat-model",
              heading: "Threat Model & Trust Boundaries",
              lead: "The system provides mathematically proven guarantees against the following institutional threats:",
              tables: {
                headers: ["Threat Vector", "Attack Mechanism", "Anchor Mitigation"],
                rows: [
                  ["Goal Hijacking & Tool Abuse", "Prompt injection forces agent to invoke unauthorized SQL delete or settlement APIs.", "Layer 2 @anchor.guard checks parameter types, maximum transaction caps, and allowed destination addresses against hard invariants."],
                  ["Statutory Risk Ceiling Breach", "Trading algorithm exceeds maximum VaR or portfolio concentration during market volatility.", "In-process Rust engine intercepts risk ratio and returns BLOCKED_BY_ANCHOR with automated rebalancing directive."],
                  ["Biometric & Emotion Profiling", "Customer support agent utilizes banned emotion classification models.", "EU AI Act Article 5 invariant halts execution and generates Critical Enforcement Notice."],
                  ["Audit Log Tampering / Repudiation", "Malicious insider alters or deletes database logs after a rogue trading event.", "DAC SHA-256 parent hash chaining and Ed25519 signing ensure any alteration immediately invalidates the Merkle root hash."],
                ],
              },
            },
          ],
        },
      },
      {
        id: "quickstart",
        title: "5-Minute Quickstart",
        badge: "Hands-on",
        description: "Install anchor-audit, instrument a Python/TypeScript agent with @anchor.guard, and verify your first DAC entry.",
        readingTime: "5 min read",
        toc: [
          { id: "prerequisites", label: "Prerequisites" },
          { id: "installation", label: "1. Install CLI & SDK" },
          { id: "instrument-code", label: "2. Instrument Agent Code" },
          { id: "run-precommit", label: "3. Run AST Static Scan" },
          { id: "verify-dac", label: "4. Verify Cryptographic Ledger" },
        ],
        content: {
          summary: "This step-by-step guide walks you through setting up Anchor in a local development environment in under 5 minutes.",
          sections: [
            {
              id: "prerequisites",
              heading: "Prerequisites",
              paragraphs: [
                "Before starting, ensure your system meets the following requirements:",
                "• Python 3.9+ or Node.js 18+ / TypeScript 5+",
                "• Rust 1.75+ (optional, required only if compiling native kernel from source)",
                "• Git 2.30+ for pre-commit hook integration",
              ],
            },
            {
              id: "installation",
              heading: "1. Install CLI & SDK",
              lead: "Install the anchor-audit CLI scanner and client runtime packages via your preferred package manager:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `# Install Python SDK and CLI Gatekeeper
pip install anchor-guard anchor-audit

# Alternatively, install Node.js / TypeScript SDK
npm install @anchor/guard @anchor/audit-cli`,
                  description: "Installs the zero-copy in-process interceptor bindings and Tree-sitter AST parser binaries.",
                },
              ],
            },
            {
              id: "instrument-code",
              heading: "2. Instrument Agent Code with @anchor.guard",
              lead: "Decorate your agent's sensitive execution boundaries with @guard. No architecture refactoring required.",
              codeSnippets: [
                {
                  language: "python",
                  filename: "trading_agent.py",
                  code: `from anchor import guard
from anchor.core.telemetry import SpokeTelemetryClient

# Step 1: Initialize the non-blocking local Spoke client
telemetry = SpokeTelemetryClient(
    hub_url="http://localhost:3000",
    identity_fingerprint="sha256:ed25519_dev_local_node_01"
)

# Step 2: Decorate your function with domain and statutory constraints
@guard(
    domain="finance",
    statutes=["SEC_REG_SCI_1001", "RBI_FREE_AI_REC06"],
    max_latency_budget_us=350,
    raise_on_violation=False
)
def execute_algorithmic_trade(portfolio_id: str, symbol: str, amount_usd: float, risk_score: float):
    """
    Anchor intercepts this function call synchronously.
    If risk_score > 0.15 or amount_usd > 100,000 without dual-key approval,
    execution is aborted before hitting the exchange.
    """
    print(f"Executing trade for {symbol}: \${amount_usd:,.2f}")
    return {"status": "SUCCESS", "tx_hash": "0x892a4f...", "amount": amount_usd}

if __name__ == "__main__":
    # Test a compliant execution
    result = execute_algorithmic_trade("PORT-901", "AAPL", 45000.0, 0.08)
    print("Compliant Result:", result)

    # Test a non-compliant execution (Risk Score 0.22 exceeds ceiling)
    blocked_result = execute_algorithmic_trade("PORT-901", "TSLA", 250000.0, 0.22)
    print("Violating Result:", blocked_result)`,
                  description: "Full working Python example demonstrating Layer 2 in-process interception.",
                },
              ],
              callouts: [
                {
                  type: "tip",
                  title: "Self-Healing Reroute Handling",
                  body: "When raise_on_violation=False, Anchor returns a structured JSON payload containing the statutory violation details, severity, and deterministic self-healing reroute directive, allowing autonomous agents to self-correct without crashing.",
                },
              ],
            },
            {
              id: "run-precommit",
              heading: "3. Run AST Static Scan",
              lead: "Verify that all agent code conforms to statutory syntax rules prior to commit:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `# Run static AST scan across current repository
anchor-audit scan ./src --frameworks EU_AI_ACT,RBI_FREE_AI --strict

# Output:
# [PASS] Layer 1 AST: Parsed 42 files across 1,840 nodes in 48ms.
# [PASS] SEC-SCI-01: Found 6 valid @guard decorators on algorithmic boundaries.
# [WARN] EU-ART14: Function 'automated_loan_underwrite' missing required human oversight override hook.
# [INFO] Exit code: 0 (All mandatory blockers cleared).`,
                },
              ],
            },
            {
              id: "verify-dac",
              heading: "4. Verify Cryptographic Ledger (DAC)",
              lead: "Verify the mathematical integrity of the append-only Decision Audit Chain:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `# Verify cryptographic hash chain integrity
anchor dac verify --local-ledger ~/.anchor/dac_local.db

# Output:
# [DAC] Validating 148 decision events across 1 Hub partition...
# [DAC] Hash 0001 (Genesis): 7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069
# [DAC] Hash 0148 (Latest):  c4ca4238a0b923820dcc509a6f75849b82877a9415ac8fd6e22f256fa0d7a94e
# [PASS] Merkle Root: 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
# [PASS] All 148 SHA-256 parent links & Ed25519 signatures mathematically intact (0 tampered).`,
                },
              ],
            },
          ],
        },
      },
      {
        id: "core-concepts",
        title: "Core Invariant Concepts",
        badge: "Theory",
        description: "Hard constraints, soft limits, self-healing rerouting, and sovereign clearance levels.",
        readingTime: "4 min read",
        toc: [
          { id: "hard-vs-soft", label: "Hard Constraints vs Soft Limits" },
          { id: "verdicts", label: "Audit Verdict Taxonomy" },
          { id: "clearance-levels", label: "Clearance Level Hierarchy" },
        ],
        content: {
          summary: "Understand the fundamental building blocks of Anchor governance: invariants, enforcement verdicts, clearance levels, and jurisdictional dialect mappings.",
          sections: [
            {
              id: "hard-vs-soft",
              heading: "Hard Constraints vs Soft Limits",
              lead: "Anchor policies categorize invariant rules into two distinct operational modes:",
              tables: {
                headers: ["Constraint Type", "Trigger Condition", "Runtime Behavior", "DAC Ledger Record"],
                rows: [
                  ["Hard Invariant (BLOCKER)", "Statutory prohibition (e.g. EU AI Act Article 5 biometric manipulation or capital limit breach).", "Instant synchronous halt. Target function never executes. Deterministic violation payload returned.", "Logged as CRITICAL_VIOLATION with signed timestamp and forensic freeze permit."],
                  ["Soft Limit (ADVISORY)", "Operational guideline or threshold warning (e.g. model confidence below 85% or high latency).", "Execution proceeds. Warning event queued asynchronously to Spoke telemetry stream.", "Logged as AUDIT_WARN with telemetry metrics."],
                  ["Conditional Override", "Action requires elevated human sign-off (e.g. loan approval > $100K).", "Execution paused pending dual-key cryptographic permit or pre-authorized token validation.", "Logged as PENDING_HUMAN_CLEARANCE -> CLEARED_BY_L3."],
                ],
              },
            },
            {
              id: "verdicts",
              heading: "Audit Verdict Taxonomy",
              lead: "Every interception generates a deterministic AuditVerdict structure:",
              codeSnippets: [
                {
                  language: "rust",
                  filename: "verdict.rs",
                  code: `#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditVerdict {
    pub is_compliant: bool,
    pub verdict_code: VerdictCode, // PASS, BLOCKED, REROUTED, PENDING_CLEARANCE
    pub execution_latency_us: u64,
    pub violation_id: Option<String>,
    pub statutory_reference: Option<String>,
    pub reroute_directive: Option<String>,
    pub signature_ed25519: String,
    pub parent_dac_hash: String,
}`,
                },
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     02. LAYER 1: STATIC AST GATEKEEPER
  ───────────────────────────────────────────────────────── */
  {
    id: "layer1-ast",
    title: "Layer 1: Static AST Gatekeeper",
    badge: "Static Analysis",
    iconName: "FileCheck",
    items: [
      {
        id: "ast-engine",
        title: "Tree-sitter Grammar & AST Engine",
        badge: "Grammar",
        description: "How Anchor constructs full syntax trees of multi-language agent codebases to enforce structural governance.",
        readingTime: "7 min read",
        toc: [
          { id: "grammar-parsing", label: "Tree-sitter Grammar Pipeline" },
          { id: "anchor-rule-spec", label: ".anchor Invariant Syntax" },
          { id: "syntax-verification", label: "Static Verification Lifecycle" },
        ],
        content: {
          summary: "Layer 1 analyzes codebase source code before runtime, ensuring that no sensitive API calls, unconstrained database writes, or unauthorized model endpoints exist without valid @guard instrumentation.",
          sections: [
            {
              id: "grammar-parsing",
              heading: "Tree-sitter Grammar Pipeline",
              lead: "Anchor utilizes custom Tree-sitter parsers for Python, TypeScript, Go, and Rust to inspect concrete syntax trees at microsecond speeds.",
              paragraphs: [
                "Unlike standard linters (Flake8, ESLint) that only check style or basic linting, the Anchor AST Gatekeeper builds a semantic governance graph of every function invocation, decorator chain, and external library import.",
                "It traverses syntax trees to locate all external execution sinks: OpenAI / Anthropic client calls, LangChain tool bindings, database queries, payment gateway SDKs, and OS process spawns.",
              ],
            },
            {
              id: "anchor-rule-spec",
              heading: ".anchor Invariant Syntax Specification",
              lead: "Governance policies are written in declarative .anchor rule files, compiled into binary AST matching trees:",
              codeSnippets: [
                {
                  language: "text",
                  filename: "FINANCE_CAPITAL_BOUNDARY.anchor",
                  code: `RULE SEC-SCI-1001:
  DOMAIN: "finance"
  JURISDICTION: "SEC_REG_SCI"
  SEVERITY: "BLOCKER"
  TARGET_AST:
    FUNCTION_CALL:
      MODULE: ["trading", "execution", "settlement"]
      PARAMETER:
        NAME: "amount_usd"
        TYPE: "float"
        CONDITION: "amount_usd <= 100000.0"
        ON_BREACH:
          ACTION: "BLOCK"
          REROUTE: "Require Dual-Key Hub Manager permit for allocations above $100,000."
  AUDIT_CHAIN:
    CAPTURE_ARGS: ["portfolio_id", "amount_usd", "risk_ratio"]
    RETENTION_YEARS: 5`,
                  description: "Declarative invariant rule defining a statutory capital limit boundary.",
                },
              ],
            },
          ],
        },
      },
      {
        id: "ci-cd-gates",
        title: "CI/CD & Pre-Commit Integration",
        badge: "Automation",
        description: "Enforce zero-regression governance gates in GitHub Actions, GitLab CI, and local git hooks.",
        readingTime: "5 min read",
        toc: [
          { id: "pre-commit", label: "Pre-commit Hook Setup" },
          { id: "github-actions", label: "GitHub Actions Workflow" },
          { id: "exit-codes", label: "CLI Exit Codes Dictionary" },
        ],
        content: {
          summary: "Block non-compliant commits and pull requests automatically in your CI/CD pipeline before code ever reaches staging or production.",
          sections: [
            {
              id: "pre-commit",
              heading: "Pre-commit Hook Setup",
              lead: "Configure .pre-commit-config.yaml to run the Anchor AST scan on every developer commit:",
              codeSnippets: [
                {
                  language: "yaml",
                  filename: ".pre-commit-config.yaml",
                  code: `repos:
  - repo: https://github.com/animuslab/anchor-audit
    rev: v6.0.2
    hooks:
      - id: anchor-ast-scan
        name: Anchor Static AST Gatekeeper
        entry: anchor-audit scan
        language: system
        args: ["--strict", "--frameworks=EU_AI_ACT,RBI_FREE_AI,SEC_REG_SCI"]
        files: \.(py|ts|tsx|go|rs)$`,
                },
              ],
            },
            {
              id: "github-actions",
              heading: "GitHub Actions Pipeline",
              lead: "Automated Pull Request audit check with statutory compliance reporting:",
              codeSnippets: [
                {
                  language: "yaml",
                  filename: ".github/workflows/anchor-governance.yml",
                  code: `name: Anchor Statutory Governance Gate
on: [push, pull_request]

jobs:
  governance-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Anchor Gatekeeper
        run: pip install anchor-audit
      - name: Execute Full AST Compliance Scan
        run: |
          anchor-audit scan ./src \\
            --strict \\
            --output-format=sarif \\
            --output-file=anchor-results.sarif
      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: anchor-results.sarif`,
                },
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     03. LAYER 2: IN-PROCESS RUNTIME INTERCEPTOR
  ───────────────────────────────────────────────────────── */
  {
    id: "layer2-runtime",
    title: "Layer 2: Runtime Interceptor",
    badge: "In-Process Core",
    iconName: "Cpu",
    items: [
      {
        id: "native-kernel",
        title: "Zero-Copy Rust Native Kernel",
        badge: "Native C-ABI",
        description: "Sub-0.4ms in-process execution boundary, memory layouts, and FFI bindings.",
        readingTime: "8 min read",
        toc: [
          { id: "kernel-lifecycle", label: "Interceptor Execution Lifecycle" },
          { id: "zero-copy-memory", label: "Zero-Copy Memory Buffer Layout" },
          { id: "benchmarks-breakdown", label: "Micro-benchmark Breakdown (< 15-350 µs)" },
        ],
        content: {
          summary: "The heart of Anchor's Layer 2 is an embedded native Rust kernel that executes synchronously inside the host application memory space via zero-copy C-ABI FFI bindings.",
          sections: [
            {
              id: "kernel-lifecycle",
              heading: "Interceptor Execution Lifecycle",
              lead: "How Anchor intercepts, validates, and records an execution in sub-350 microseconds:",
              paragraphs: [
                "1. Intake & Serialization: Host SDK (@anchor.guard) intercepts function arguments and writes memory pointers to a contiguous zero-copy byte buffer.",
                "2. FFI Pass to Native Rust Core: The pointer is passed across the C-ABI boundary into the pre-warmed Rust memory segment without heap allocations.",
                "3. Invariant Matching: Rust engine evaluates compiled rule bytecodes against argument values, domain bounds, and statutory dialects.",
                "4. Verdict Branching: If PASS, returns execution to the host function immediately (< 15 µs). If BLOCK, intercepts execution flow and emits self-healing payload.",
                "5. Asynchronous DAC Enqueue: State event is serialized and dispatched to a lock-free background ring buffer for Ed25519 signing and Hub telemetry streaming.",
              ],
            },
            {
              id: "benchmarks-breakdown",
              heading: "Micro-benchmark Breakdown",
              lead: "Rigorous performance benchmarks executed across 1,000,000 simulated agent decisions on standard cloud infrastructure (AWS c6i.2xlarge):",
              tables: {
                headers: ["Interceptor Stage", "Median Latency (p50)", "99th Percentile (p99)", "Max (p99.9)"],
                rows: [
                  ["Zero-Copy Buffer Serialization", "3.2 microseconds", "8.4 microseconds", "14.1 microseconds"],
                  ["Rust Invariant Bytecode Match", "9.1 microseconds", "24.6 microseconds", "48.2 microseconds"],
                  ["Lock-Free Ring Buffer DAC Enqueue", "2.4 microseconds", "5.1 microseconds", "8.9 microseconds"],
                  ["Total In-Process Interception Overhead", "14.7 microseconds", "38.1 microseconds", "71.2 microseconds"],
                  ["Legacy LLM-as-a-Judge Baseline", "640,000 microseconds (640ms)", "1,850,000 microseconds (1.85s)", "3,400,000 microseconds (3.4s)"],
                ],
                caption: "Anchor introduces negligible (< 0.04ms) latency, making it 16,000x faster than remote LLM evaluations.",
              },
            },
          ],
        },
      },
      {
        id: "python-sdk",
        title: "Python SDK (@anchor.guard)",
        badge: "Python SDK",
        description: "Complete guide to instrumenting Python AI agents, LangChain tools, and FastAPI handlers.",
        readingTime: "6 min read",
        toc: [
          { id: "decorator-api", label: "@guard Decorator API" },
          { id: "langchain-integration", label: "LangChain & LlamaIndex Tools" },
          { id: "error-handling", label: "Exception Suppression & Rerouting" },
        ],
        content: {
          summary: "The Python SDK provides an ergonomic @guard decorator and client utilities designed for modern AI frameworks including LangChain, LlamaIndex, AutoGen, and CrewAI.",
          sections: [
            {
              id: "decorator-api",
              heading: "@guard Decorator API & Parameters",
              lead: "Signature and parameter reference for anchor.guard:",
              codeSnippets: [
                {
                  language: "python",
                  filename: "decorator_spec.py",
                  code: `def guard(
    domain: str,                          # Target regulatory domain ('finance', 'health', 'banking', 'ops')
    statutes: List[str] = None,           # Explicit statute codes ('EU_AI_ACT_ART14', 'RBI_FREE_AI_REC06')
    max_latency_budget_us: int = 350,     # Maximum permitted interceptor latency budget in microseconds
    raise_on_violation: bool = False,     # If False, returns structured dict instead of raising GovernanceViolationException
    custom_evaluator: Callable = None,    # Optional in-process Python callback for domain logic
    fallback_reroute: Callable = None     # Optional self-healing fallback function
):
    ...`,
                },
              ],
            },
            {
              id: "langchain-integration",
              heading: "LangChain Tool Guarding",
              lead: "Protecting autonomous agent tools from prompt injection and rogue SQL queries:",
              codeSnippets: [
                {
                  language: "python",
                  filename: "langchain_tool.py",
                  code: `from langchain.tools import tool
from anchor import guard

@tool
@guard(domain="banking", statutes=["RBI_FREE_AI_REC06", "EU_AI_ACT_ART14"])
def transfer_funds(account_from: str, account_to: str, amount_inr: float) -> str:
    """Transfers funds between internal bank accounts."""
    # If the LLM generates a transfer > ₹500,000 without 2FA token,
    # Anchor intercepts before database update.
    return f"Successfully transferred ₹{amount_inr:,.2f} to {account_to}."`,
                },
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     04. DECISION AUDIT CHAIN (DAC)
  ───────────────────────────────────────────────────────── */
  {
    id: "decision-audit-chain",
    title: "Decision Audit Chain (DAC)",
    badge: "Cryptographic Ledger",
    iconName: "Lock",
    items: [
      {
        id: "dac-math",
        title: "Merkle Tree & SHA-256 Chaining Math",
        badge: "Cryptography",
        description: "Mathematical formulation of parent hash chaining, payload normalization, and Ed25519 signing.",
        readingTime: "7 min read",
        toc: [
          { id: "merkle-formulation", label: "Mathematical Formulation" },
          { id: "event-schema", label: "DAC Event Schema" },
          { id: "subpoena-readiness", label: "Subpoena & Audit Readiness" },
        ],
        content: {
          summary: "The Decision Audit Chain (DAC) is an append-only, tamper-evident cryptographic ledger that binds every AI action to its preceding state, timestamp epoch, and node identity key.",
          sections: [
            {
              id: "merkle-formulation",
              heading: "Mathematical Formulation of DAC Event Block",
              lead: "Every event block H(n) in the Decision Audit Chain is computed deterministically as:",
              paragraphs: [
                "Let H_prev be the SHA-256 digest of the immediately preceding event block.",
                "Let P_canon be the canonical JSON serialization (RFC 8785) of the execution payload (arguments, verdicts, metadata).",
                "Let T_epoch be the Unix millisecond timestamp.",
                "Let K_pub be the Ed25519 public key of the executing Spoke Node.",
                "The event block hash H_curr is formulated as: H_curr = SHA-256( H_prev || P_canon || T_epoch || K_pub )",
                "The node generates an Ed25519 digital signature: S_curr = Sign( K_priv, H_curr ). Any tampering with past events invalidates all subsequent hashes across the chain.",
              ],
            },
            {
              id: "event-schema",
              heading: "Canonical DAC Event Schema",
              lead: "JSON structure of an immutable Decision Record stored in the ledger:",
              codeSnippets: [
                {
                  language: "json",
                  filename: "dac_event_record.json",
                  code: `{
  "dac_index": 98214,
  "parent_hash": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "block_hash": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
  "timestamp_iso": "2026-09-02T14:32:01.819Z",
  "node_id": "spoke-node-mum01",
  "node_ed25519_pub": "MCowBQYDK2VwAyEA9Y+m6L...",
  "domain": "finance",
  "function_name": "execute_algorithmic_trade",
  "arguments_hash": "3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b",
  "verdict": {
    "status": "PASS",
    "latency_us": 24,
    "evaluated_rules": ["SEC-SCI-1001", "RBI-FREE-AI-06"]
  },
  "signature": "3045022100892a4f6d..."
}`,
                },
              ],
            },
          ],
        },
      },
      {
        id: "replay-permits",
        title: "Replay Permits & Dual-Key Workflows",
        badge: "Security",
        description: "How Hub Managers and compliance officers issue cryptographically scoped forensic replay tokens.",
        readingTime: "5 min read",
        toc: [
          { id: "dual-key-workflow", label: "Dual-Key Cryptographic Protocol" },
          { id: "replay-token-generation", label: "Replay Token Generation" },
        ],
        content: {
          summary: "To protect sensitive production data while enabling thorough forensic investigations, Anchor employs time-limited, cryptographic Replay Access Permits requiring dual-key manager authorization.",
          sections: [
            {
              id: "dual-key-workflow",
              heading: "Dual-Key Cryptographic Authorization",
              lead: "Sensitive forensic reviews (such as unmasking PII or replaying high-value transactions) require sign-off from two independent clearance holders:",
              paragraphs: [
                "1. Requestor: Standard Auditor (L1) or Project Lead (L2) submits a formal ReplayRequest with justification and target DAC block range.",
                "2. Approver: Hub Manager (L3) verifies justification and applies their Ed25519 administrative private key to generate an ephemeral permit.",
                "3. Token Verification: The Spoke Node validates both signatures before decrypting argument payloads for replay.",
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     05. JURISDICTIONAL DIALECT COMPILER
  ───────────────────────────────────────────────────────── */
  {
    id: "jurisdictions",
    title: "Jurisdictional Dialect Compiler",
    badge: "Statutory Law",
    iconName: "Scale",
    items: [
      {
        id: "eu-ai-act",
        title: "EU AI Act (Articles 9–99) Compliance",
        badge: "EU Regulation",
        description: "Complete mapping of European Union Artificial Intelligence Act mandates to hard runtime invariants.",
        readingTime: "8 min read",
        toc: [
          { id: "prohibited-practices", label: "Article 5: Prohibited AI Practices" },
          { id: "high-risk-obligations", label: "Articles 9–15: High-Risk AI Requirements" },
          { id: "human-oversight", label: "Article 14: Hard Human Oversight Gates" },
        ],
        content: {
          summary: "Anchor translates the European Union AI Act statutory text directly into formal executable invariants, providing out-of-the-box compliance for high-risk AI deployments.",
          sections: [
            {
              id: "prohibited-practices",
              heading: "Article 5: Prohibited AI Practices (Strict Zero-Tolerance)",
              lead: "Anchor contains hard-coded invariant blockers that immediately halt execution if an agent engages in prohibited practices:",
              tables: {
                headers: ["EU AI Act Article", "Prohibited Practice", "Anchor Invariant Rule", "Action"],
                rows: [
                  ["Art. 5(1)(a)", "Subliminal behavioral manipulation causing harm.", "EU-ART05-SUBLIMINAL", "BLOCK + Emit Statutory Violation Notice"],
                  ["Art. 5(1)(c)", "Social scoring of natural persons.", "EU-ART05-SOCIAL-SCORE", "BLOCK + Freeze Model Spoke Session"],
                  ["Art. 5(1)(f)", "Biometric emotion categorization in workplace/education.", "EU-ART05-EMOTION-CAT", "BLOCK + Dual-Key Revocation"],
                ],
              },
            },
            {
              id: "high-risk-obligations",
              heading: "Articles 9–15: High-Risk System Mandatory Controls",
              lead: "Mandatory technical requirements enforced at the API and codebase level:",
              paragraphs: [
                "• Article 9 (Risk Management System): Dynamic parameter bounding and continuous telemetry anomaly detection.",
                "• Article 10 (Data & Governance): Verification that training/inference inputs do not contain unredacted PII.",
                "• Article 12 (Record-Keeping & Logging): Continuous, automatic logging to the Decision Audit Chain with minimum 5-year cryptographic retention.",
                "• Article 14 (Human Oversight): Hard architectural kill-switch (@anchor.human_override) enabling designated human operators to halt or override agentic execution in real-time.",
              ],
            },
          ],
        },
      },
      {
        id: "rbi-free-ai",
        title: "RBI FREE-AI (26 Recommendations)",
        badge: "India Regulation",
        description: "Reserve Bank of India FREE-AI framework for Indian banks, NBFCs, and fintech payment providers.",
        readingTime: "7 min read",
        toc: [
          { id: "rbi-framework-overview", label: "RBI FREE-AI Architecture" },
          { id: "lending-invariants", label: "Algorithmic Lending & Credit Invariants" },
          { id: "cims-export", label: "Automated RBI CIMS Filing Exports" },
        ],
        content: {
          summary: "Full support for the Reserve Bank of India's 26 FREE-AI (Fairness, Reliability, Explainability, Ethics in AI) recommendations, with specialized Indian banking dialects.",
          sections: [
            {
              id: "rbi-framework-overview",
              heading: "RBI FREE-AI Core Invariant Rules",
              lead: "Key statutory rules enforced for Indian commercial banks and NBFCs:",
              tables: {
                headers: ["Recommendation", "Principle", "Anchor Implementation", "Mandatory Threshold"],
                rows: [
                  ["Rec 04", "Algorithmic Fairness", "Demographic parity check across pin-code and socio-economic parameters.", "Max disparate impact ratio <= 0.80."],
                  ["Rec 06", "Explainability & Auditability", "Synchronous capture of feature importance weights into DAC block.", "SHAP/TreeSHAP values bound to every loan verdict."],
                  ["Rec 11", "Runaway Risk Prevention", "Automated daily and per-transaction capital allocation limits.", "Hard block on credit disbursements > ₹10,00,000 without L3 clearance."],
                  ["Rec 22", "Customer Recourse & Appeal", "Automated generation of Human Replay Dossiers for rejected applicants.", "One-click export in statutory dialect."],
                ],
              },
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     06. SDK & API REFERENCE
  ───────────────────────────────────────────────────────── */
  {
    id: "sdk-api-reference",
    title: "SDK & API Reference",
    badge: "API Manual",
    iconName: "Code2",
    items: [
      {
        id: "python-library-api",
        title: "Python SDK (anchor-py) Reference",
        badge: "anchor-py",
        description: "Comprehensive class and method documentation for anchor.guard, SpokeTelemetryClient, and DialectCompiler.",
        readingTime: "10 min read",
        toc: [
          { id: "spoke-client-class", label: "SpokeTelemetryClient Class" },
          { id: "guard-decorator-spec", label: "guard() Method" },
          { id: "exceptions-reference", label: "Exceptions & Error Codes" },
        ],
        content: {
          summary: "Complete API manual for the Python SDK with exhaustive method signatures, parameter tables, and typed return definitions (Palantir Transforms style).",
          sections: [
            {
              id: "spoke-client-class",
              heading: "Class: SpokeTelemetryClient",
              lead: "Manages asynchronous, non-blocking telemetry communication between local agent processes and the Anchor Governance Hub.",
              codeSnippets: [
                {
                  language: "python",
                  filename: "anchor/core/telemetry.py",
                  code: `class SpokeTelemetryClient:
    def __init__(
        self,
        hub_url: str = "http://localhost:3000",
        identity_fingerprint: str = None,
        buffer_size: int = 10000,
        flush_interval_ms: int = 250,
        air_gapped_mode: bool = False
    ) -> None:
        """
        Initializes the telemetry client.
        
        Parameters:
        - hub_url (str): Destination URL of the Anchor Hub or local Spoke Node.
        - identity_fingerprint (str): SHA-256 hash of the node's Ed25519 public key.
        - buffer_size (int): Ring buffer capacity for event queuing (default: 10,000).
        - flush_interval_ms (int): Background batch flush frequency in milliseconds.
        - air_gapped_mode (bool): If True, persists events to local SQLite ledger only.
        """
        ...`,
                },
              ],
            },
            {
              id: "exceptions-reference",
              heading: "Exceptions & Error Code Dictionary",
              lead: "Standard exception classes raised when raise_on_violation=True:",
              tables: {
                headers: ["Exception Class", "Error Code", "HTTP Status", "Description"],
                rows: [
                  ["StatutoryViolationException", "ERR_STATUTE_BREACH", "403 Forbidden", "Triggered when a hard statutory rule (e.g. EU AI Act Article 5) is violated."],
                  ["CapitalBoundaryException", "ERR_CAPITAL_CEILING", "400 Bad Request", "Triggered when transaction volume exceeds pre-authorized quota."],
                  ["LatencyBudgetExceededException", "ERR_LATENCY_OVERRUN", "504 Gateway Timeout", "Triggered when in-process verification exceeds max_latency_budget_us."],
                  ["TamperedDacChainException", "ERR_DAC_CORRUPTION", "500 Internal Error", "Triggered if local parent hash does not match previous Merkle node."],
                ],
              },
            },
          ],
        },
      },
      {
        id: "typescript-sdk-api",
        title: "TypeScript SDK (@anchor/guard)",
        badge: "@anchor/guard",
        description: "Typed interfaces and runtime guard wrappers for Node.js, Next.js, and TypeScript worker agents.",
        readingTime: "8 min read",
        toc: [
          { id: "ts-guard-wrapper", label: "anchorGuard() Function" },
          { id: "ts-telemetry-client", label: "SpokeTelemetryClient (TypeScript)" },
          { id: "ts-types-reference", label: "TypeScript Type Definitions" },
        ],
        content: {
          summary: "Complete API manual for the TypeScript/Node.js SDK with full generic type definitions and async execution wrappers.",
          sections: [
            {
              id: "ts-guard-wrapper",
              heading: "Function: anchorGuard()",
              lead: "Higher-order wrapper for Node.js and Edge runtime agent functions:",
              codeSnippets: [
                {
                  language: "typescript",
                  filename: "index.ts",
                  code: `import { anchorGuard, AuditVerdict } from "@anchor/guard";

export const executeSettlement = anchorGuard(
  {
    domain: "finance",
    statutes: ["SEC_REG_SCI_1001", "RBI_FREE_AI_REC06"],
    maxLatencyBudgetUs: 350,
    raiseOnViolation: false
  },
  async (portfolioId: string, amountUsd: number, riskScore: number) => {
    // Target settlement logic executes only if Anchor returns PASS
    return { status: "EXECUTED", txId: "tx_8912a", amount: amountUsd };
  }
);`,
                },
              ],
            },
          ],
        },
      },
      {
        id: "cli-manual",
        title: "CLI Reference (anchor-audit & anchor-node)",
        badge: "CLI Tool",
        description: "Full command-line manual for scanning codebases, verifying DAC chains, and starting Hub nodes.",
        readingTime: "6 min read",
        toc: [
          { id: "cli-scan-command", label: "anchor-audit scan" },
          { id: "cli-dac-command", label: "anchor dac verify" },
          { id: "cli-hub-command", label: "anchor hub start" },
        ],
        content: {
          summary: "Reference guide for all Anchor command-line utilities, flags, environment variables, and exit codes.",
          sections: [
            {
              id: "cli-scan-command",
              heading: "Command: anchor-audit scan",
              lead: "Runs static AST gatekeeper analysis across repository files:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `Usage: anchor-audit scan [OPTIONS] <TARGET_PATH>

Options:
  -s, --strict             Exit with code 1 on any warning or advisory violation.
  -f, --frameworks TEXT    Comma-separated statutory frameworks (EU_AI_ACT,RBI_FREE_AI,SEC_REG_SCI).
  -o, --output-format TEXT Output format: table, json, sarif, csv [default: table].
  -r, --rules-dir PATH     Custom directory containing .anchor rule files.
  --fix                    Attempt automated AST insertion of missing @guard decorators.
  -h, --help               Show this message and exit.`,
                },
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     07. GOVERNANCE HUB & SPOKE MESH
  ───────────────────────────────────────────────────────── */
  {
    id: "hub-mesh",
    title: "Governance Hub & Spoke Mesh",
    badge: "Infrastructure",
    iconName: "Server",
    items: [
      {
        id: "clearance-sovereignty",
        title: "Clearance Hierarchy (L1–L4)",
        badge: "Security Roles",
        description: "Deep dive into role permissions, cryptographic key management, and administrative sovereignty.",
        readingTime: "7 min read",
        toc: [
          { id: "clearance-matrix", label: "Clearance Level Taxonomy" },
          { id: "sovereignty-rules", label: "Hub Sovereignty & Node Topology" },
          { id: "key-delegation", label: "Ed25519 Key Registration & Rotation" },
        ],
        content: {
          summary: "Anchor enforces access control and liability attribution through an explicit cryptographic clearance hierarchy.",
          sections: [
            {
              id: "clearance-matrix",
              heading: "Clearance Level Taxonomy & Permissions",
              lead: "The four institutional clearance tiers and their operational boundaries:",
              tables: {
                headers: ["Clearance Level", "Role Name", "Cryptographic Authority", "Scope Boundary"],
                rows: [
                  ["Level 1 (L1)", "Developer", "Signs local pre-commit AST scans & registers Ed25519 agent node identity.", "Project-scoped code & models."],
                  ["Level 1 (L1)", "Standard Auditor", "Read-only access to single-hub DAC ledger & issues formal EnforcementNotice tickets.", "Single-Hub forensic scope."],
                  ["Level 2 (L2)", "Project Lead", "Rotates project API keys, triages violation logs, and requests elevated permits.", "Multi-project branch scope."],
                  ["Level 2 (L2)", "Cross-Hub Auditor", "Enterprise-wide DAC explorer, inter-hub mesh auditing & consolidated filings.", "Multi-Hub global scope."],
                  ["Level 3 (L3)", "Hub Manager", "Dual-key permit approvals, clearance sovereignty, and dialect configuration.", "Apex branch container."],
                  ["Level 4 (L4)", "Root Authority / Regulator", "External forensic pulls & statutory subpoena enforcement permits.", "Statutory oversight authority."],
                ],
              },
            },
          ],
        },
      },
      {
        id: "air-gap-deployment",
        title: "Air-Gapped & Sovereign Deployment",
        badge: "Air-Gapped",
        description: "Zero external egress topologies, on-premise SQLite/PostgreSQL storage, and air-gapped license provisioning.",
        readingTime: "6 min read",
        toc: [
          { id: "air-gap-topology", label: "Zero-Egress Network Architecture" },
          { id: "air-gap-compose", label: "Docker Compose On-Prem Stack" },
        ],
        content: {
          summary: "Deploy Anchor entirely inside an isolated VPC or physical air-gapped data center with guaranteed zero outbound telemetry.",
          sections: [
            {
              id: "air-gap-topology",
              heading: "Zero-Egress Network Architecture",
              lead: "How Anchor functions with zero internet connectivity:",
              paragraphs: [
                "1. Embedded Invariant Bundles: All statutory dialect rules (EU AI Act, RBI, SEC) are compiled into offline binary blobs signed with AnimusLab's root public key.",
                "2. Local Spoke Node Cache: Spoke Nodes run alongside your agent services, caching rules in local memory and persisting DAC blocks to an internal PostgreSQL or SQLite cluster.",
                "3. Sovereign Hub UI: Hub Managers and Auditors access the dashboard over internal enterprise LAN or VPN.",
              ],
            },
          ],
        },
      },
    ],
  },

  /* ─────────────────────────────────────────────────────────
     08. ENTERPRISE RUNBOOKS & TROUBLESHOOTING
  ───────────────────────────────────────────────────────── */
  {
    id: "runbooks",
    title: "Enterprise Runbooks",
    badge: "Runbooks",
    iconName: "Terminal",
    items: [
      {
        id: "latency-profiling",
        title: "Zero-Copy Latency Profiling",
        badge: "Tuning",
        description: "Step-by-step runbook for profiling in-process interceptors and optimizing C-ABI memory allocations.",
        readingTime: "5 min read",
        toc: [
          { id: "perf-tracing", label: "1. Enable High-Resolution Microsecond Tracing" },
          { id: "memory-pinning", label: "2. Memory Buffer Pre-Allocation" },
        ],
        content: {
          summary: "Diagnose and optimize interceptor execution latency to maintain sub-100 microsecond overhead under heavy agentic loads.",
          sections: [
            {
              id: "perf-tracing",
              heading: "1. Enable Microsecond Tracing",
              lead: "Configure the in-process tracer to emit microsecond breakdown telemetry:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `# Export high-precision telemetry environment flag
export ANCHOR_PERF_TRACE=1
export ANCHOR_RING_BUFFER_CAPACITY=50000

# Run agent workload with profiling summary
python -m anchor.tools.profile_agent ./src/trading_agent.py --iterations 10000`,
                },
              ],
            },
          ],
        },
      },
      {
        id: "subpoena-readiness",
        title: "Statutory Audit Dossier Export",
        badge: "Compliance Runbook",
        description: "One-click generation of mathematically sealed compliance packages for RBI, SEC, or EU AI Act regulators.",
        readingTime: "5 min read",
        toc: [
          { id: "dossier-export-command", label: "Exporting Certified Audit Dossiers" },
          { id: "cryptographic-verification", label: "Regulator Verification Protocol" },
        ],
        content: {
          summary: "Generate self-contained, cryptographically signed audit packages ready for statutory submission to regulatory examiners.",
          sections: [
            {
              id: "dossier-export-command",
              heading: "Exporting Certified Audit Dossiers",
              lead: "Run the dossier export CLI command for target audit periods:",
              codeSnippets: [
                {
                  language: "bash",
                  filename: "terminal",
                  code: `# Export certified RBI FREE-AI audit dossier for Q3 2026
anchor dac export \\
  --start-epoch 2026-07-01 \\
  --end-epoch 2026-09-30 \\
  --dialect RBI_CIMS \\
  --sign-with-manager-key ~/.anchor/manager_ed25519.pem \\
  --output-package rbi_q3_2026_audit.anchor_dossier`,
                },
              ],
            },
          ],
        },
      },
    ],
  },
];
