"""add_parent_entry_id_to_ledger

Revision ID: 1c2d0ad56c1e
Revises: 7fd0af5f6169
Create Date: 2026-04-02 03:36:29.491101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2d0ad56c1e'
down_revision: Union[str, Sequence[str], None] = '7fd0af5f6169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger', sa.Column('parent_entry_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ledger', 'ledger', ['parent_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ledger', type_='foreignkey')
    op.drop_column('ledger', 'parent_entry_id')
    # ### end Alembic commands ###
