"""initial_schema_with_webhook_columns

Revision ID: 33329c46832f
Revises: 
Create Date: 2026-04-02 00:03:25.339782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33329c46832f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('chain_hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ledger')
    op.drop_table('entities')
    # ### end Alembic commands ###
