"""add_multi_subscription_infrastructure

Revision ID: 7fd0af5f6169
Revises: 33329c46832f
Create Date: 2026-04-02 01:44:43.798720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd0af5f6169'
down_revision: Union[str, Sequence[str], None] = '33329c46832f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('webhook_url', sa.String(), nullable=True),
    sa.Column('webhook_secret', sa.String(), nullable=True),
    sa.Column('dialect', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('entities', 'webhook_url')
    op.drop_column('entities', 'webhook_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('webhook_secret', sa.VARCHAR(), nullable=True))
    op.add_column('entities', sa.Column('webhook_url', sa.VARCHAR(), nullable=True))
    op.drop_table('webhook_subscriptions')
    # ### end Alembic commands ###
